Repository gardener/gardener-extension-registry-cache, pull requests merged in 2023-12, with the labels that each got.

#103 Nit: `./hack/check-skaffold-deps.sh update`
  skaffold.yaml
Labels: cla: yes, lgtm, size/L, approved, kind/cleanup

#109 Switch the systemd unit type from `oneshot` to `simple`
  pkg/webhook/operatingsystemconfig/ensurer.go
  pkg/webhook/operatingsystemconfig/ensurer_test.go
  test/common/common.go
Labels: cla: yes, size/S, lgtm, approved, kind/enhancement

#114 Fix CPM for Shoot with registry-cache extension enabled
  pkg/component/registrycaches/registry_caches.go
  pkg/controller/extension/actuator.go
Labels: cla: yes, size/S, kind/bug, lgtm, area/control-plane-migration, approved

#112 Add monitoring dashboard for registry cache persistent volumes
  pkg/component/registrycaches/monitoring.go
  pkg/component/registrycaches/monitoring/dashboard.json
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, lgtm, size/L, approved, area/monitoring, kind/enhancement

#116 Adapt unit tests, e2e tests and docs for the GCR -> Artifact Registry switch
  docs/usage/configuration.md
  docs/usage/upstream-credentials.md
  pkg/apis/registry/helper/helper_test.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registryconfigurationcleaner/registry_configuration_cleaner_test.go
  pkg/component/registryconfigurationcleaner/testdata/daemonset-with-psp-enabled.yaml
  pkg/component/registryconfigurationcleaner/testdata/daemonset-with-systemd-unit.yaml
  pkg/component/registryconfigurationcleaner/testdata/daemonset-without-systemd-unit.yaml
  pkg/utils/registry/registry_test.go
  pkg/webhook/operatingsystemconfig/ensurer_test.go
  test/common/common.go
  test/e2e/create_enabled_delete_shoot_system_components_test.go
Labels: cla: yes, lgtm, size/L, approved, kind/cleanup

#118 Fix the testmachinery test for arm64 Shoots
  test/common/common.go
  test/e2e/create_enable_add_remove_disable_delete_test.go
  test/e2e/create_enabled_force_delete_test.go
  test/e2e/create_enabled_hibernate_reconcile_delete_test.go
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
Labels: cla: yes, size/M, kind/bug, lgtm, approved, area/testing

#119 Vendor gardener/gardener@v1.84.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/hack/check-imports.sh
  vendor/github.com/gardener/gardener/hack/generate-crds.sh
  vendor/github.com/gardener/gardener/hack/kind-up.sh
  vendor/github.com/gardener/gardener/hack/update-codegen.sh
  vendor/github.com/gardener/gardener/hack/update-protobuf.sh
  vendor/github.com/gardener/gardener/hack/vgopath-setup.sh
  vendor/modules.txt
Labels: cla: yes, size/L, approved, kind/enhancement
