Repository gardener/gardener-extension-registry-cache, pull requests merged in 2023-09, with the labels that each got.

#37 Add `hack/tools/bin/.gitkeep`. Fix `make extension-up`. Deflake the e2e tests
  Makefile
  hack/tools/bin/.gitkeep
  test/e2e/common_test.go
Labels: cla: yes, size/S, kind/bug, lgtm, approved

#31 Sync charts with latest changes
  charts/admission/charts/runtime/templates/deployment.yaml
  charts/admission/charts/runtime/templates/service.yaml
  charts/admission/charts/runtime/templates/vpa.yaml
  charts/admission/values.yaml
  charts/gardener-extension-registry-cache/templates/deployment.yaml
  charts/gardener-extension-registry-cache/templates/vpa.yaml
  charts/gardener-extension-registry-cache/values.yaml
  charts/registration/templates/controller-registration.yaml
  cmd/gardener-extension-registry-cache-admission/app/app.go
  cmd/gardener-extension-registry-cache/app/app.go
  cmd/gardener-extension-registry-cache/app/options.go
  example/registration/controller-registration.yaml
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#36 Extract the registry deployment into component. Add missing unit tests
  cmd/gardener-extension-registry-cache-admission/app/app.go
  cmd/gardener-extension-registry-cache/app/app.go
  pkg/admission/validator/serialization.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/shoot_test.go
  pkg/admission/validator/webhook.go
  pkg/apis/config/v1alpha1/defaults.go
  pkg/apis/registry/v1alpha1/types.go
  pkg/apis/registry/validation/validation.go
  pkg/apis/registry/validation/validation_test.go
  pkg/cmd/options.go
  pkg/component/registrycaches/registrycaches.go
  pkg/component/registrycaches/registrycaches_suite_test.go
  pkg/component/registrycaches/registrycaches_test.go
  pkg/constants/constants.go
  pkg/controller/extension/actuator.go
  pkg/controller/extension/add.go
  pkg/controller/registrydeployer.go
  vendor/github.com/gardener/gardener/pkg/mock/controller-runtime/client/doc.go
  vendor/github.com/gardener/gardener/pkg/mock/controller-runtime/client/mocks.go
  vendor/github.com/gardener/gardener/pkg/utils/retry/fake/retry.go
  vendor/github.com/gardener/gardener/pkg/utils/test/gomock.go
  vendor/github.com/gardener/gardener/pkg/utils/test/manager.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/conditions.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/deep.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/fields.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/kubernetes_errors.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/matchers.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/reference.go
  vendor/github.com/gardener/gardener/pkg/utils/test/options.go
  vendor/github.com/gardener/gardener/pkg/utils/test/test.go
  vendor/github.com/gardener/gardener/pkg/utils/test/test_resources.go
  vendor/go.uber.org/mock/gomock/call.go
  vendor/go.uber.org/mock/gomock/callset.go
  vendor/go.uber.org/mock/gomock/controller.go
  vendor/go.uber.org/mock/gomock/doc.go
  vendor/go.uber.org/mock/gomock/matchers.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved, kind/enhancement

#40 Improve the skaffold setup of the extension. Fix `make extension-down`
  Makefile
  charts/admission/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-registry-cache/doc.go
  charts/gardener-extension-registry-cache/templates/_helpers.tpl
  charts/gardener-extension-registry-cache/templates/deployment.yaml
  charts/gardener-extension-registry-cache/values.yaml
  charts/registration/Chart.yaml
  charts/registration/templates/controller-registration.yaml
  charts/registration/values.yaml
  docs/development/getting-started-locally.md
  example/00-config.yaml
  example/40-validatingwebhookconfiguration.yaml
  example/admission/tls.crt
  example/admission/tls.key
  example/controller-registration.yaml
  example/registration/controller-registration.yaml
  example/registration/kustomization.yaml
  example/registration/patch-deployment.yaml
  example/registration/patch-registration.yaml
  hack/ci-e2e-kind.sh
  hack/dev-setup-admission-registry-cache.sh
  skaffold-admission.yaml
  skaffold.yaml
Labels: cla: yes, lgtm, size/L, approved, area/dev-productivity, kind/enhancement

#39 Use `1.21.0` instead of `1.21` as module version
  Makefile
  go.mod
Labels: cla: yes, size/XS, kind/bug, lgtm, approved

#46 Update registry image
  charts/images.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#49 Vendor gardener/gardener@v1.77.5
  Makefile
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/hack/compare-k8s-admission-plugins.sh
  vendor/github.com/gardener/gardener/hack/compare-k8s-feature-gates.sh
  vendor/github.com/gardener/gardener/hack/tools.mk
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved, kind/enhancement

#52 Use `kube-system` namespace to deploy registry cache extension
  pkg/component/registrycaches/registrycaches.go
  pkg/component/registrycaches/registrycaches_test.go
  pkg/constants/constants.go
  pkg/controller/extension/actuator.go
  test/e2e/common_test.go
Labels: cla: yes, size/M, area/metering, lgtm, approved, area/logging, kind/enhancement
