Repository gardener/gardener-extension-registry-cache, pull requests merged in 2023-11, with the labels that each got.

#84 Extend the default e2e test to test upstream addition and removal
  pkg/apis/registry/helper/helper_test.go
  test/common/common.go
  test/e2e/create_enable_add_remove_disable_delete_test.go
  test/e2e/create_enabled_delete_shoot_system_components_test.go
  test/e2e/create_enabled_hibernate_reconcile_delete_test.go
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
Labels: cla: yes, lgtm, size/L, approved, area/testing, kind/enhancement

#89 Skip vulnerability scans for the alpine and pause images
  imagevector/images.yaml
Labels: cla: yes, size/S, lgtm, approved, kind/enhancement

#91 Use debian 12 (bookworm) distroless image as base image
  Dockerfile
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#81 Add docs for developers
  README.md
  docs/development/extension-registry-cache.md
  docs/usage/configuration.md
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#83 Do not deploy the `registry-configuration-cleaner` on Shoot deletion
  docs/development/extension-registry-cache.md
  pkg/controller/extension/actuator.go
  test/e2e/create_enable_force_delete_test.go
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#94 Add support for private image access
  README.md
  charts/admission/charts/application/templates/rbac.yaml
  charts/admission/charts/runtime/templates/deployment.yaml
  docs/usage/configuration.md
  docs/usage/upstream-credentials.md
  example/shoot.yaml
  go.mod
  hack/api-reference/registry.md
  pkg/admission/validator/shoot.go
  pkg/admission/validator/shoot_test.go
  pkg/admission/validator/webhook.go
  pkg/apis/registry/types.go
  pkg/apis/registry/v1alpha1/helper/helper.go
  pkg/apis/registry/v1alpha1/helper/helper_test.go
  pkg/apis/registry/v1alpha1/types.go
  pkg/apis/registry/v1alpha1/zz_generated.conversion.go
  pkg/apis/registry/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/registry/validation/validation.go
  pkg/apis/registry/validation/validation_test.go
  pkg/apis/registry/zz_generated.deepcopy.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
  pkg/controller/extension/actuator.go
  skaffold.yaml
Labels: cla: yes, kind/api-change, size/XXL, lgtm, approved

#98 Fix the `--version` flag
  .dockerignore
  Dockerfile
  Makefile
  cmd/gardener-extension-registry-cache-admission/app/app.go
  cmd/gardener-extension-registry-cache/app/app.go
  skaffold.yaml
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#96 Add alerts for registry caches' volumes
  charts/gardener-extension-registry-cache/templates/clusterrole.yaml
  example/controller-registration.yaml
  pkg/component/registrycaches/alerting-rules/registry-cache.rules.yaml
  pkg/component/registrycaches/monitoring.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, lgtm, size/L, approved, area/monitoring, kind/enhancement

#100 Fix exit code handling for the `hack/check-skaffold-deps.sh` script
  hack/check-skaffold-deps.sh
Labels: cla: yes, size/XS, kind/bug, lgtm, approved

#102 force deletion e2e test: Create the Shoot with enabled extension
  test/common/common.go
  test/e2e/create_enabled_force_delete_test.go
Labels: cla: yes, size/S, lgtm, approved, kind/enhancement
