Repository gardener/gardener-extension-registry-cache, pull requests merged in 2023-03, with the labels that each got.

#13 Clean up RBAC rules for `dnsrecords`
  charts/gardener-extension-registry-cache/templates/rbac.yaml
  charts/registration/templates/controller-registration.yaml
  example/registration/controller-registration.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup

#14 Adapt `NetworkPolicy` rules according to recent refactorings
  charts/gardener-extension-registry-cache/templates/deployment.yaml
  charts/gardener-extension-registry-cache/templates/service.yaml
  charts/registration/templates/controller-registration.yaml
  example/registration/controller-registration.yaml
Labels: cla: yes, size/M, area/security, area/networking, lgtm, approved, area/dev-productivity, area/ops-productivity, kind/enhancement

#16 Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  cmd/gardener-extension-registry-cache/app/app.go
  go.mod
  go.sum
  pkg/cmd/options.go
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healthcheck_actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/inject.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/message_util.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: cla: yes, area/control-plane, size/XXL, kind/bug, lgtm, approved

#17 Switched from DockerHub to Gardener GCR
  charts/images.yaml
Labels: cla: yes, size/XS, area/networking, lgtm, approved, kind/enhancement, ok-to-test
