Repository gardener/gardener-extension-registry-cache, pull requests merged in 2023-10, with the labels that each got.

#47 Set `priorityClassName` for the registry cache Pods
  pkg/component/registrycaches/registrycaches.go
  pkg/component/registrycaches/registrycaches_test.go
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#53 Change the `garbageCollectionEnabled` field to `garbageCollection.enabled`
  example/shoot.yaml
  hack/api-reference/registry.md
  pkg/apis/registry/types.go
  pkg/apis/registry/v1alpha1/defaults.go
  pkg/apis/registry/v1alpha1/helper/helper.go
  pkg/apis/registry/v1alpha1/helper/helper_test.go
  pkg/apis/registry/v1alpha1/types.go
  pkg/apis/registry/v1alpha1/zz_generated.conversion.go
  pkg/apis/registry/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/registry/validation/validation_test.go
  pkg/apis/registry/zz_generated.deepcopy.go
  pkg/component/registrycaches/registrycaches.go
  pkg/component/registrycaches/registrycaches_test.go
Labels: cla: yes, lgtm, size/L, approved, kind/enhancement

#55 Add readiness and liveness probe to the registry Pods
  pkg/component/registrycaches/registrycaches.go
  pkg/component/registrycaches/registrycaches_test.go
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#57 skaffold: Rebuild when there are changes to `go:embed` files
  Makefile
  hack/check-skaffold-deps.sh
  skaffold.yaml
Labels: cla: yes, lgtm, size/L, approved, area/dev-productivity, kind/enhancement

#42 Make the cache size field immutable
  pkg/admission/validator/helper.go
  pkg/admission/validator/helper_test.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/shoot_test.go
  pkg/apis/registry/helper/helper.go
  pkg/apis/registry/helper/helper_test.go
  pkg/apis/registry/validation/validation.go
  pkg/apis/registry/validation/validation_test.go
  skaffold.yaml
Labels: cla: yes, lgtm, size/L, approved, kind/enhancement

#63 Move `charts/images.yaml` to `imagevector/images.yaml`
  .dockerignore
  Dockerfile
  charts/images.go
  imagevector/images.yaml
  imagevector/imagevector.go
  pkg/controller/extension/actuator.go
  skaffold.yaml
Labels: cla: yes, size/M, lgtm, approved, area/dev-productivity, kind/cleanup

#64 Bump registry from 2.8.2 to 2.8.3
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: cla: yes, size/XS, lgtm, approved, area/open-source, kind/enhancement

#67 Clean up TODO
  charts/gardener-extension-registry-cache/templates/service.yaml
  example/controller-registration.yaml
  example/shoot.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup

#51 Explicitly set the PVC's `storageClassName` to `default`
  go.mod
  go.sum
  pkg/apis/registry/helper/helper_test.go
  pkg/component/registrycaches/registrycaches.go
  pkg/component/registrycaches/registrycaches_test.go
  vendor/modules.txt
Labels: cla: yes, size/S, kind/bug, lgtm, approved

#72 Adapt the extension chart
  charts/gardener-extension-registry-cache/templates/deployment.yaml
  charts/gardener-extension-registry-cache/templates/vpa.yaml
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#73 Add support for projected volume kubeconfig
  charts/admission/charts/runtime/templates/deployment.yaml
  charts/admission/values.yaml
Labels: cla: yes, size/M, area/security, lgtm, approved, kind/enhancement

#70 Clean up unused value
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup

#74 Address TODO related to admission Pod labels
  charts/admission/charts/runtime/templates/deployment.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup

#71 Define VPA managed resources requests for registry pull through caches
  charts/admission/charts/runtime/templates/vpa.yaml
  charts/admission/values.yaml
  charts/gardener-extension-registry-cache/templates/vpa.yaml
  example/controller-registration.yaml
  go.mod
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/controller/extension/actuator.go
Labels: cla: yes, lgtm, size/L, approved, area/auto-scaling, kind/enhancement

#76 Reduce e2e test flakes due to transient network errors
  test/common/common.go
Labels: cla: yes, size/S, kind/bug, lgtm, approved, area/testing

#78 Change the webhook port from 10251 to 10250
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
Labels: cla: yes, size/XS, kind/bug, lgtm, approved

#44 Add docs for end users
  docs/usage/configuration.md
  docs/usage/images/shoot-cluster-with-registry-cache.png
  docs/usage/images/shoot-cluster-without-registry-cache.png
Labels: cla: yes, lgtm, size/L, approved, kind/enhancement

#80 Change the imageVectorOverwrite value type from string to object
  charts/gardener-extension-registry-cache/templates/configmap-imagevector-overwrite.yaml
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
Labels: cla: yes, size/S, lgtm, area/usability, approved, kind/enhancement

#86 fix: Concourse build badge URL
  README.md
Labels: cla: yes, size/XS, lgtm, area/documentation, approved, kind/cleanup

#82 Deflake the e2e tests
  test/common/common.go
Labels: cla: yes, size/M, kind/bug, lgtm, approved
