Repository gardener/gardener-extension-registry-cache, pull requests merged in 2023-01, with the labels that each got.

#7 Update kubernetes docs reference to 1.25
  hack/api-reference/config.json
  hack/api-reference/registry.json
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup, area/open-source

#6 Add pipeline definitions
  .ci/component_descriptor
  .ci/pipeline_definitions
  .ci/prepare_release
  .ci/verify
Labels: cla: yes, size/M, lgtm, approved, area/delivery, kind/enhancement

#8 Do not publish images in the head-update job
  .ci/pipeline_definitions
  README.md
Labels: cla: yes, size/S, lgtm, approved, area/delivery, kind/enhancement

#9 Set reasonable version for first release
  VERSION
  charts/registration/templates/controller-registration.yaml
  example/registration/controller-registration.yaml
Labels: cla: yes, size/XS, lgtm, approved, area/delivery, kind/enhancement
