Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-07, with the labels that each got.

#221 Comment out the custom storageClassName field in the usage docs
  docs/usage/registry-cache/configuration.md
Labels: cla: yes, size/XS, lgtm, area/documentation, approved, kind/enhancement

#225 e2e && tm tests: Increase ginkgo timeouts
  .test-defs/TestSuiteRegistryCacheBetaSerial.yaml
  hack/test-e2e-local.sh
Labels: cla: yes, size/XS, lgtm, approved, area/testing, kind/enhancement

#224 Update registry to 3.0.0-beta.1
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#228 Replace use of `docker.io` with `public.ecr.aws` to avoid docker hub pull rate limit errors
  test/common/common.go
  test/e2e/cache/create_enable_add_remove_disable_delete.go
  test/e2e/cache/create_enabled_force_delete.go
  test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
Labels: cla: yes, size/M, lgtm, approved, area/testing, kind/enhancement
