Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-12, with the labels that each got.

#301 Increase the `e2e-cache-ssc` e2e test create shoot context timeout to 15 minutes
  test/e2e/cache/create_enabled_delete_shoot_system_components.go
Labels: cla: yes, size/XS, kind/flake, lgtm, approved, area/testing

#302 Rework the component unit tests to use the managedResourceObjectsMatcher
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  test/e2e/cache/create_enable_for_private_registry_delete.go
  test/e2e/common.go
Labels: cla: yes, size/XL, lgtm, approved, area/dev-productivity, area/testing, kind/enhancement

#245 Configure TLS communication between registry cache and containerd
  charts/gardener-extension-registry-cache/templates/clusterrole.yaml
  example/controller-registration.yaml
  hack/api-reference/registry.md
  pkg/apis/registry/types.go
  pkg/apis/registry/v1alpha3/types.go
  pkg/apis/registry/v1alpha3/zz_generated.conversion.go
  pkg/component/registrycaches/export_test.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
  pkg/component/registrycacheservices/registry_cache_services.go
  pkg/component/registrycacheservices/registry_cache_services_test.go
  pkg/controller/cache/actuator.go
  pkg/secrets/config.go
  pkg/secrets/config_test.go
  pkg/utils/registry/registry.go
  pkg/utils/registry/registry_test.go
  pkg/webhook/cache/ensurer.go
  pkg/webhook/cache/ensurer_test.go
  skaffold.yaml
Labels: cla: yes, area/security, size/XXL, lgtm, approved, kind/enhancement, area/ipcei, ipcei/registry-cache-extension

#308 extension and admission: Improve templating the VPA resource
  charts/admission/charts/runtime/templates/vpa.yaml
  charts/admission/values.yaml
  charts/gardener-extension-registry-cache/templates/vpa.yaml
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
Labels: cla: yes, area/quality, size/S, lgtm, approved, kind/enhancement

#306 Clean up the unused `pkg/controller/config` pkg
  pkg/controller/config/config.go
Labels: cla: yes, size/S, lgtm, approved, kind/cleanup

#285 Add CA rotation TM test
  .test-defs/TestSuiteRegistryCacheBetaSerial.yaml
  test/common/common.go
  test/testmachinery/shoot/enable_rotate_ca_disable_test.go
Labels: cla: yes, lgtm, size/L, approved, kind/test, area/testing

#309 Update registry to 3.0.0-rc.2
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
  test/e2e/cache/create_enable_for_private_registry_delete.go
Labels: cla: yes, size/S, lgtm, approved, kind/enhancement
