Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-03, with the labels that each got.

#121 Drop support for Shoots with Kubernetes version == 1.24
  charts/admission/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-registry-cache/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registryconfigurationcleaner/registry_configuration_cleaner.go
  pkg/component/registryconfigurationcleaner/registry_configuration_cleaner_test.go
  pkg/component/registryconfigurationcleaner/testdata/clusterrole-psp.yaml
  pkg/component/registryconfigurationcleaner/testdata/daemonset-with-psp-enabled.yaml
  pkg/component/registryconfigurationcleaner/testdata/daemonset-with-systemd-unit.yaml
  pkg/component/registryconfigurationcleaner/testdata/daemonset-without-systemd-unit.yaml
  pkg/component/registryconfigurationcleaner/testdata/podsecuritypolicy.yaml
  pkg/component/registryconfigurationcleaner/testdata/rolebinding-psp.yaml
  pkg/component/registryconfigurationcleaner/testdata/serviceaccount.yaml
  pkg/controller/cache/actuator.go
Labels: cla: yes, size/XL, lgtm, approved, kind/cleanup

#162 Activate registry graceful shutdown
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
Labels: cla: yes, size/S, lgtm, approved, area/robustness, kind/enhancement

#151 Clean up v1alpha2 usages
  pkg/admission/validator/cache/shoot_test.go
  pkg/admission/validator/mirror/shoot_test.go
  pkg/controller/cache/actuator.go
  pkg/webhook/cache/ensurer_test.go
  test/common/common.go
  test/e2e/cache/create_enable_add_remove_disable_delete.go
  test/e2e/cache/create_enabled_delete_shoot_system_components.go
  test/e2e/cache/create_enabled_force_delete.go
  test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
Labels: cla: yes, lgtm, size/L, approved, kind/cleanup

#159 Documentation enhancement
  README.md
  docs/development/extension-registry-cache.md
  docs/development/getting-started-locally.md
  docs/usage/registry-cache/configuration.md
  docs/usage/registry-cache/upstream-credentials.md
  docs/usage/registry-mirror/configuration.md
Labels: cla: yes, lgtm, size/L, area/documentation, approved, kind/enhancement

#167 Update alpine
  imagevector/images.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#169 Add recording rules that will be federated by aggregate prometheus and garden-prometheus
  pkg/component/registrycaches/alerting-rules/registry-cache.rules.yaml
Labels: cla: yes, size/XS, lgtm, approved, area/monitoring, kind/enhancement

#173 Always delete the config cleaner MR when the extension is deleted
  pkg/controller/cache/actuator.go
Labels: cla: yes, size/S, kind/bug, lgtm, approved

#165 Remove the v1alpha2 API
  README.md
  docs/usage/registry-cache/migration-from-v1alpha2-to-v1alpha3.md
  hack/update-codegen.sh
  pkg/apis/registry/install/install.go
  pkg/apis/registry/v1alpha2/conversions.go
  pkg/apis/registry/v1alpha2/conversions_test.go
  pkg/apis/registry/v1alpha2/defaults.go
  pkg/apis/registry/v1alpha2/defaults_test.go
  pkg/apis/registry/v1alpha2/doc.go
  pkg/apis/registry/v1alpha2/register.go
  pkg/apis/registry/v1alpha2/types.go
  pkg/apis/registry/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/registry/v1alpha2/zz_generated.conversion.go
  pkg/apis/registry/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/registry/v1alpha2/zz_generated.defaults.go
  skaffold.yaml
Labels: cla: yes, size/XL, lgtm, approved, kind/cleanup
