Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-08, with the labels that each got.

#227 Use `OperatingSystemConfig` API to configure `containerd` registries and drop custom systemd unit and `registryconfigurationcleaner` daemonset
  docs/development/extension-registry-cache.md
  docs/usage/registry-cache/configuration.md
  go.mod
  imagevector/images.yaml
  pkg/component/registryconfigurationcleaner/registry_configuration_cleaner.go
  pkg/component/registryconfigurationcleaner/registry_configuration_cleaner_suite_test.go
  pkg/component/registryconfigurationcleaner/registry_configuration_cleaner_test.go
  pkg/component/registryconfigurationcleaner/testdata/daemonset-with-systemd-unit.yaml
  pkg/component/registryconfigurationcleaner/testdata/daemonset-without-systemd-unit.yaml
  pkg/controller/cache/actuator.go
  pkg/webhook/cache/ensurer.go
  pkg/webhook/cache/ensurer_test.go
  pkg/webhook/cache/scripts/configure-containerd-registries.sh
  pkg/webhook/mirror/ensurer.go
  pkg/webhook/mirror/ensurer_test.go
  pkg/webhook/mirror/templates/hosts.toml.tpl
  skaffold.yaml
  test/common/common.go
  test/e2e/cache/create_enable_add_remove_disable_delete.go
  test/e2e/cache/create_enabled_delete_shoot_system_components.go
  test/e2e/cache/create_enabled_force_delete.go
  test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
  test/e2e/mirror/create_enable_disable_delete.go
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
Labels: cla: yes, size/XXL, lgtm, approved, area/robustness, kind/enhancement

#237 Cleanup TODOs related to legacy monitoring configuration
  charts/gardener-extension-registry-cache/templates/clusterrole.yaml
  example/controller-registration.yaml
  pkg/component/registrycaches/alerting-rules/registry-cache.rules.yaml
  pkg/component/registrycaches/monitoring.go
  pkg/component/registrycaches/registry_caches_test.go
  skaffold.yaml
Labels: cla: yes, lgtm, size/L, approved, kind/cleanup, area/monitoring

#241 Fixed broken links - 2024.08
  docs/usage/registry-cache/configuration.md
Labels: cla: yes, size/XS, lgtm, area/documentation, approved, kind/enhancement
