Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-02, with the labels that each got.

#138 Update registry to 3.0.0-alpha.1
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#140 Clean up v1alpha1 usages from tests
  pkg/admission/validator/cache/shoot_test.go
  pkg/admission/validator/mirror/shoot_test.go
  pkg/webhook/cache/ensurer_test.go
  test/common/common.go
  test/e2e/cache/create_enable_add_remove_disable_delete.go
  test/e2e/cache/create_enabled_delete_shoot_system_components.go
  test/e2e/cache/create_enabled_force_delete.go
  test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
Labels: cla: yes, lgtm, size/L, approved, kind/cleanup

#142 Replace usages of deprecated pointer functions
  go.mod
  go.sum
  pkg/admission/validator/cache/shoot_test.go
  pkg/apis/registry/helper/helper_test.go
  pkg/apis/registry/v1alpha1/conversions.go
  pkg/apis/registry/v1alpha1/conversions_test.go
  pkg/apis/registry/validation/validation_test.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registryconfigurationcleaner/registry_configuration_cleaner.go
  pkg/component/registryconfigurationcleaner/registry_configuration_cleaner_test.go
  pkg/webhook/cache/ensurer.go
  pkg/webhook/cache/ensurer_test.go
  pkg/webhook/mirror/ensurer.go
  pkg/webhook/mirror/ensurer_test.go
  test/e2e/common.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/modules.txt
Labels: cla: yes, size/XL, lgtm, approved, kind/cleanup

#141 Remove the v1alpha1 API
  README.md
  docs/usage/registry-cache/migration-from-v1alpha1-to-v1alpha2.md
  docs/usage/registry-mirror/configuration.md
  hack/update-codegen.sh
  pkg/apis/registry/install/install.go
  pkg/apis/registry/v1alpha1/conversions.go
  pkg/apis/registry/v1alpha1/conversions_test.go
  pkg/apis/registry/v1alpha1/defaults.go
  pkg/apis/registry/v1alpha1/defaults_test.go
  pkg/apis/registry/v1alpha1/doc.go
  pkg/apis/registry/v1alpha1/register.go
  pkg/apis/registry/v1alpha1/types.go
  pkg/apis/registry/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/registry/v1alpha1/zz_generated.conversion.go
  pkg/apis/registry/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/registry/v1alpha1/zz_generated.defaults.go
  skaffold.yaml
Labels: cla: yes, size/XL, lgtm, approved, kind/cleanup

#150 Fix link to contributor guide
  CONTRIBUTING.md
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup

#110 Add scrape config and monitoring dashboard
  pkg/component/registrycaches/monitoring.go
  pkg/component/registrycaches/monitoring/dashboard.json
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, size/XL, lgtm, approved, lifecycle/frozen, area/monitoring, kind/enhancement

#148 Add CVE categorisation for the registry image
  imagevector/images.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#153 Add titles to the docs
  docs/development/extension-registry-cache.md
  docs/development/getting-started-locally.md
  docs/usage/registry-cache/configuration.md
  docs/usage/registry-cache/migration-from-v1alpha2-to-v1alpha3.md
  docs/usage/registry-cache/upstream-credentials.md
  docs/usage/registry-mirror/configuration.md
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement

#152 Improve the upstream credentials docs
  .ci/third_party/component_descriptor
  .ci/third_party/prepare_release
  docs/usage/registry-cache/configuration.md
  docs/usage/registry-cache/upstream-credentials.md
Labels: cla: yes, size/S, lgtm, approved, kind/enhancement

#149 Add note about available alerts and how to enable notifications for them
  docs/development/extension-registry-cache.md
  docs/usage/registry-cache/configuration.md
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#158 Fix links to gardener/gardener docs
  docs/development/extension-registry-cache.md
  docs/development/getting-started-locally.md
  docs/usage/registry-cache/configuration.md
  docs/usage/registry-cache/migration-from-v1alpha2-to-v1alpha3.md
  docs/usage/registry-cache/upstream-credentials.md
  docs/usage/registry-mirror/configuration.md
Labels: cla: yes, size/M, lgtm, area/documentation, approved, kind/enhancement
