Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-09, with the labels that each got.

#250 Nit: Switch notes to the new notes syntax in Github
  docs/usage/registry-cache/configuration.md
  docs/usage/registry-cache/upstream-credentials.md
Labels: cla: yes, size/XS, lgtm, area/documentation, approved, kind/enhancement

#254 Replace use of `public.ecr.aws/nginx/nginx` with `ghcr.io/jitesoft/alpine` image
  docs/usage/registry-cache/configuration.md
  test/common/common.go
  test/e2e/cache/create_enable_add_remove_disable_delete.go
  test/e2e/cache/create_enabled_force_delete.go
  test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
Labels: cla: yes, kind/flake, lgtm, size/L, approved, area/testing

#258 pipeline_definitions: Don't build and push images and charts on pull requests
  .ci/pipeline_definitions
Labels: cla: yes, size/S, lgtm, approved, kind/cleanup, area/delivery, needs/ok-to-test

#257 make extension-down: Delete the validating webhook of the admission component
  Makefile
Labels: cla: yes, size/XS, lgtm, approved, area/dev-productivity, kind/enhancement

#260 Document that the image pull Secrets should not be removed when using registry cache with credentials
  docs/usage/registry-cache/upstream-credentials.md
Labels: cla: yes, size/XS, lgtm, area/documentation, approved, kind/enhancement
