Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-11, with the labels that each got.

#279 Fix skaffold tag generation to generate a new tag on code changes (without local commit)
  Makefile
  skaffold.yaml
Labels: cla: yes, size/S, kind/bug, lgtm, approved, area/dev-productivity

#280 Increase parallel execution of e2e tests from 2 to 3
  Makefile
Labels: cla: yes, size/XS, lgtm, approved, area/testing, kind/enhancement

#277 Fix `make extension-up`
  skaffold.yaml
Labels: cla: yes, size/S, kind/bug, lgtm, approved, area/dev-productivity

#273 Fix broken links
  docs/development/extension-registry-cache.md
Labels: cla: yes, size/S, lgtm, approved, kind/cleanup

#272 Enable gosec for static application security testing
  .ci/pipeline_definitions
  .gitignore
  Makefile
Labels: cla: yes, size/M, lgtm, approved, kind/enhancement, area/compliance

#292 Overwrite registry image ENTRYPOINT to avoid `panic` when `scheduler-state.json` file is corrupted.
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, size/M, lgtm, approved, area/robustness, kind/enhancement

#294 skaffold: Remove custom `tagPolicy` for the admission
  skaffold.yaml
Labels: cla: yes, size/S, lgtm, approved, area/dev-productivity, kind/cleanup

#296 Don't specify by default `maxAllowed` for extension and admission VPAs
  charts/admission/charts/runtime/templates/vpa.yaml
  charts/admission/values.yaml
  charts/gardener-extension-registry-cache/templates/vpa.yaml
  charts/gardener-extension-registry-cache/values.yaml
  example/controller-registration.yaml
Labels: cla: yes, size/M, lgtm, approved, kind/cleanup, area/auto-scaling

#246 Add proxy support for registry cache
  docs/usage/registry-cache/configuration.md
  hack/api-reference/registry.md
  pkg/apis/registry/types.go
  pkg/apis/registry/v1alpha3/types.go
  pkg/apis/registry/v1alpha3/zz_generated.conversion.go
  pkg/apis/registry/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/registry/validation/validation.go
  pkg/apis/registry/validation/validation_test.go
  pkg/apis/registry/zz_generated.deepcopy.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, lgtm, size/L, area/usability, approved, kind/enhancement
