Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-06, with the labels that each got.

#211 Remove the `DeleteOnInvalidUpdate` annotation
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, size/XS, lgtm, approved, area/dev-productivity, kind/cleanup

#213 admission: Lower `revisionHistoryLimit` to 2
  charts/admission/charts/runtime/templates/deployment.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#210 Add validation early exit when no semantic change in providerConfig is detected
  docs/usage/registry-cache/upstream-credentials.md
  pkg/admission/validator/cache/shoot.go
  pkg/admission/validator/cache/shoot_test.go
Labels: cla: yes, size/M, lgtm, approved, area/ops-productivity, kind/enhancement
