Repository gardener/gardener-extension-registry-cache, pull requests merged in 2024-10, with the labels that each got.

#255 Improve image pull check
  test/common/common.go
Labels: cla: yes, size/M, lgtm, approved, area/testing, kind/enhancement

#266 Fixed broken link
  docs/usage/registry-mirror/configuration.md
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#270 Clean up usages of the already removed `shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds` annotation
  example/shoot-registry-cache.yaml
  example/shoot-registry-mirror.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup
