Repository gardener/gardener-extension-registry-cache, pull requests merged in 2025-02, with the labels that each got.

#334 dependabot: Ignore go rc versions
  .github/dependabot.yaml
Labels: cla: yes, size/XS, lgtm, approved, kind/enhancement

#331 Make the TLS feature configurable for a registry cache
  docs/usage/registry-cache/configuration.md
  hack/api-reference/registry.md
  hack/test-e2e-local.sh
  pkg/apis/registry/helper/helper.go
  pkg/apis/registry/helper/helper_test.go
  pkg/apis/registry/types.go
  pkg/apis/registry/v1alpha3/defaults.go
  pkg/apis/registry/v1alpha3/defaults_test.go
  pkg/apis/registry/v1alpha3/types.go
  pkg/apis/registry/v1alpha3/zz_generated.conversion.go
  pkg/apis/registry/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/registry/zz_generated.deepcopy.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
  pkg/component/registrycacheservices/registry_cache_services.go
  pkg/component/registrycacheservices/registry_cache_services_test.go
  pkg/constants/constants.go
  pkg/controller/cache/actuator.go
  pkg/secrets/config.go
  pkg/webhook/cache/ensurer.go
  pkg/webhook/cache/ensurer_test.go
  test/e2e/cache/create_disable_tls_enable_tls_delete.go
Labels: cla: yes, size/XL, area/security, lgtm, approved, kind/enhancement

#336 Add DNS service names in secret config
  pkg/secrets/config.go
Labels: cla: yes, area/security, size/XS, kind/bug, lgtm, approved

#340 Clean up duplicate RBAC rule
  charts/gardener-extension-registry-cache/templates/clusterrole.yaml
  example/controller-registration.yaml
Labels: cla: yes, area/quality, size/XS, lgtm, approved, kind/cleanup

#339 Fix reconciliciation for a cache with a long upstream
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/secrets/config.go
  pkg/secrets/config_test.go
  pkg/utils/registry/registry.go
  pkg/utils/registry/registry_test.go
Labels: cla: yes, area/quality, kind/bug, lgtm, size/L, approved

#344 Fix a race condition that could occur while switching between TLS enabled and disabled
  .dockerignore
  pkg/component/registrycacheservices/registry_cache_services.go
  pkg/component/registrycacheservices/registry_cache_services_test.go
  pkg/controller/cache/actuator.go
  pkg/controller/cache/add.go
  skaffold.yaml
  third_party/gardener/gardener/pkg/utils/managedresources/managedresources.go
Labels: cla: yes, area/quality, size/M, kind/bug, lgtm, approved

#330 tests: Do not wait 30s for the alpine Pod to be deleted
  test/common/common.go
  test/e2e/cache/create_disable_tls_enable_tls_delete.go
  test/e2e/cache/create_enable_add_remove_disable_delete.go
  test/e2e/cache/create_enable_for_private_registry_delete.go
  test/e2e/cache/create_enabled_force_delete.go
  test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
  test/testmachinery/shoot/enable_rotate_ca_disable_test.go
Labels: cla: yes, size/M, lgtm, approved, area/testing, kind/enhancement

#346 e2e: Use a cache with a long upsteam in the force deletion e2e test
  test/e2e/cache/create_enabled_force_delete.go
Labels: cla: yes, size/XS, lgtm, approved, area/testing, kind/enhancement

#347 Revert "dependabot: Ignore go rc versions"
  .github/dependabot.yaml
Labels: cla: yes, size/XS, lgtm, approved, area/dev-productivity, kind/cleanup

#356 Fix tagging of extension image for remote dev setup
  Makefile
Labels: cla: yes, size/XS, kind/bug, lgtm, approved, area/dev-productivity

#351 e2e tests: Disable VPA for the e2e test Shoots
  test/e2e/common.go
Labels: cla: yes, size/S, lgtm, approved, area/testing, kind/enhancement

#355 Update registry to 3.0.0-rc.3
  charts/gardener-extension-registry-cache/values.yaml
  docs/usage/registry-cache/observability.md
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
  test/e2e/cache/create_enable_for_private_registry_delete.go
Labels: cla: yes, size/S, lgtm, approved, kind/enhancement

#303 Improve the check for Node bootstrap issue
  test/e2e/cache/create_enable_for_private_registry_delete.go
  test/e2e/cache/create_enabled_delete_shoot_system_components.go
Labels: cla: yes, size/M, kind/flake, lgtm, approved, area/testing

#359 Run `skaffold fix`
  skaffold.yaml
Labels: cla: yes, size/M, lgtm, approved, area/dev-productivity, kind/cleanup

#274 Drop support for Shoots with Kubernetes version <= 1.26
  charts/admission/charts/runtime/templates/poddisruptionbudget.yaml
  charts/admission/charts/runtime/templates/service.yaml
  charts/gardener-extension-registry-cache/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
Labels: cla: yes, size/S, lgtm, approved, kind/cleanup

#314 Promote `testmachinery` tests to GA
  .test-defs/TestSuiteRegistryCacheSerial.yaml
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
  test/testmachinery/shoot/enable_rotate_ca_disable_test.go
Labels: cla: yes, size/S, lgtm, approved, area/testing, kind/enhancement

#363 Annotate registry cache StatefulSet with the `reference.resources.gardener.cloud/secret-<hash>` annotation
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, area/quality, size/M, kind/bug, lgtm, approved

#365 Annotate registry cache StatefulSet with the `reference.resources.gardener.cloud/secret-<hash>` annotation to prevent Secrets marked as garbage collectable from being deleted
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, area/quality, size/M, kind/bug, lgtm, approved

#361 Add `extension-operator-up` make target
  Makefile
  charts/admission/charts/runtime/templates/_helpers.tpl
  charts/admission/charts/runtime/values.yaml
  docs/development/getting-started-locally.md
  hack/check-skaffold-deps.sh
  local-setup/operator-extension-resource.yaml
  skaffold-operator.yaml
Labels: cla: yes, lgtm, size/L, approved, area/dev-productivity, kind/enhancement

#366 Fix reuse compliance
  .reuse/dep5
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup
