Repository gardener/gardener-extension-registry-cache, pull requests merged in 2025-05, with the labels that each got.

#396 Add PodDistruptionBudget when HA is enabled
  pkg/apis/registry/helper/helper.go
  pkg/apis/registry/helper/helper_test.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, size/M, area/high-availability, lgtm, approved, kind/enhancement

#399 tm tests: Add expectation framework's Shoot client not to be nil
  test/testmachinery/shoot/enable_disable_test.go
  test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
  test/testmachinery/shoot/enable_rotate_ca_disable_test.go
Labels: cla: yes, size/S, lgtm, approved, area/testing, kind/enhancement

#394 Cleanup TODOs related to removing Services from extension-registry-cache ManagedResource
  charts/gardener-extension-registry-cache/templates/clusterrole.yaml
  example/controller-registration.yaml
  pkg/controller/cache/actuator.go
Labels: cla: yes, lgtm, size/L, approved, kind/cleanup
