Repository gardener/gardener-extension-registry-cache, pull requests merged in 2025-06, with the labels that each got.

#400 Sync `.ci/third_party` scripts
  .ci/third_party/component_descriptor
Labels: cla: yes, size/S, lgtm, approved, kind/cleanup, area/delivery

#410 Bump github.com/gardener/gardener from 1.116.4 to 1.117.6
  go.mod
  go.sum
Labels: cla: yes, lgtm, size/L, approved, area/open-source, kind/enhancement

#412 Bump github.com/gardener/gardener from 1.118.3 to 1.119.1
  go.mod
  go.sum
Labels: cla: yes, size/M, lgtm, approved, area/open-source, kind/enhancement

#419 Clean up ineffective assignment
  pkg/controller/mirror/add.go
Labels: cla: yes, area/quality, size/XS, lgtm, approved, kind/cleanup
