Repository gardener/gardener-extension-registry-cache, pull requests merged in 2025-09, with the labels that each got.

#448 Add generation for `Extension` example
  Makefile
  example/doc.go
  example/extension.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/extension-patch.yaml
  example/extension/kustomization.yaml
Labels: cla: yes, size/M, lgtm, approved, area/ops-productivity, kind/enhancement, area/ipcei

#425 Allow configuring registry cache service name
  docs/usage/registry-cache/configuration.md
  hack/api-reference/registry.md
  pkg/apis/registry/types.go
  pkg/apis/registry/v1alpha3/types.go
  pkg/apis/registry/v1alpha3/zz_generated.conversion.go
  pkg/apis/registry/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/registry/validation/validation.go
  pkg/apis/registry/validation/validation_test.go
  pkg/apis/registry/zz_generated.deepcopy.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycacheservices/registry_cache_services.go
  pkg/component/registrycacheservices/registry_cache_services_test.go
  pkg/utils/registry/registry.go
  pkg/utils/registry/registry_test.go
  skaffold-operator.yaml
  skaffold.yaml
  test/e2e/cache/create_enabled_force_delete.go
Labels: cla: yes, lgtm, size/L, area/usability, approved, kind/enhancement

#459 Fix monitoring `ScrapeConfig` roles
  pkg/component/registrycaches/monitoring.go
Labels: cla: yes, size/XS, kind/bug, lgtm, approved, area/monitoring

#455 Remove `spec.serviceName` and add `spec.revisionHistoryLimit=2` fields in the registry `StatefulSet`
  pkg/apis/registry/validation/validation.go
  pkg/apis/registry/validation/validation_test.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, area/quality, size/M, lgtm, approved, kind/enhancement

#465 Set up git identity for `run-linter` GitHub action
  .github/workflows/build.yaml
Labels: cla: yes, size/XS, kind/bug, lgtm, approved, area/delivery
