Repository gardener/gardener-extension-registry-cache, pull requests merged in 2025-01, with the labels that each got.

#311 cleanup: drop unused codepath
  .ci/third_party/component_descriptor
Labels: cla: yes, size/S, lgtm, approved, kind/cleanup, area/delivery

#313 Fix a cyrillic character in the header
  docs/usage/registry-cache/configuration.md
Labels: cla: yes, size/XS, lgtm, approved, kind/cleanup

#321 Make decoding of `Raw` to configs consistent
  pkg/cmd/options.go
  pkg/controller/cache/actuator.go
  pkg/webhook/cache/ensurer.go
  pkg/webhook/mirror/ensurer.go
Labels: cla: yes, area/quality, size/XS, lgtm, approved, kind/enhancement

#324 Fix a corner case in the non-TLS to TLS registry-cache migration
  pkg/component/registrycaches/registry_caches_test.go
  pkg/controller/cache/actuator.go
Labels: cla: yes, area/quality, kind/bug, lgtm, size/L, approved

#326 Add monitoring documentation
  README.md
  docs/usage/registry-cache/configuration.md
  docs/usage/registry-cache/observability.md
Labels: cla: yes, size/M, lgtm, area/documentation, approved, kind/enhancement
