Repository gardener/gardener-extension-registry-cache, pull requests merged in 2025-04, with the labels that each got.

#298 Add optional high availability feature for registry cache
  docs/usage/registry-cache/configuration.md
  hack/api-reference/registry.md
  pkg/apis/registry/types.go
  pkg/apis/registry/v1alpha3/types.go
  pkg/apis/registry/v1alpha3/zz_generated.conversion.go
  pkg/apis/registry/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/registry/zz_generated.deepcopy.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, area/high-availability, lgtm, size/L, approved, kind/enhancement

#389 Address PR review suggestions for #298
  docs/usage/registry-cache/configuration.md
  hack/api-reference/registry.md
  pkg/apis/registry/types.go
  pkg/apis/registry/v1alpha3/types.go
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, size/M, area/high-availability, lgtm, approved, kind/enhancement

#388 Update registry to 3.0.0
  charts/gardener-extension-registry-cache/values.yaml
  docs/usage/registry-cache/observability.md
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
  test/e2e/cache/create_enable_for_private_registry_delete.go
Labels: cla: yes, size/S, lgtm, approved, area/open-source, kind/enhancement

#395 Remove maxAllowed from the registry cache VPA
  pkg/component/registrycaches/registry_caches.go
  pkg/component/registrycaches/registry_caches_test.go
Labels: cla: yes, size/XS, lgtm, approved, area/auto-scaling, kind/enhancement

#393 Restrict RBAC permissions
  charts/admission/charts/application/templates/rbac.yaml
  charts/admission/charts/runtime/templates/rbac.yaml
  charts/gardener-extension-registry-cache/templates/clusterrole.yaml
  charts/gardener-extension-registry-cache/templates/role.yaml
  example/controller-registration.yaml
Labels: cla: yes, size/M, area/security, lgtm, approved, kind/enhancement
