Repository gardener/gardener-extension-registry-cache, pull requests merged in 2025-03, with the labels that each got.

#370 skaffold: Clean up no longer needed custom `tagPolicy`
  Makefile
  skaffold-operator.yaml
  skaffold.yaml
Labels: cla: yes, size/S, lgtm, approved, area/dev-productivity, kind/cleanup

#374 tests: User varargs for passing commands to the RootPodExecutor
  test/common/common.go
  test/e2e/cache/create_enable_for_private_registry_delete.go
  test/e2e/cache/create_enabled_delete_shoot_system_components.go
Labels: cla: yes, size/S, lgtm, approved, kind/cleanup, area/testing

#323 Use ServiceTrafficDistribution to make Services topology-aware when runtime Kubernetes >= 1.31
  charts/admission/charts/runtime/templates/service.yaml
Labels: cla: yes, size/XS, area/networking, area/high-availability, lgtm, approved, kind/enhancement

#380 Update registry to 3.0.0-rc.4
  charts/gardener-extension-registry-cache/values.yaml
  docs/usage/registry-cache/observability.md
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/component/registrycaches/registry_caches_test.go
  pkg/component/registrycaches/templates/config.yml.tpl
  test/e2e/cache/create_enable_for_private_registry_delete.go
Labels: cla: yes, size/S, lgtm, approved, area/open-source, kind/enhancement
